name = "Pak"
desc = "Wrapper written in Go designed for package managers to unify software management commands between distros"

[dependencies]
brew = []
apt = []
dnf = []
yum = []
zypper = []
yay = []
pacman = []

[scripts]
build = "build.sh"
install = "install.sh"
remove = "remove.sh"
